name: Release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  macos-arm-release:
    name: MacOS Release
    runs-on: macos-12
    steps:
      - uses: actions/checkout@master
      - name: check toolchain
        run: rustup default
      - name: Build
        run: |
          cargo build --release
      - name: tar
        run: tar --directory=target/release -cf archive.tar.gz openpgp-card-init
      - name: upload
        run: |
          id=$(gh api -H "Accept: application/vnd.github+json" /repos/jnaulty/openpgp-card-init/releases/tags/${{ github.ref_name }} --jq .id)
          curl --fail-with-body -sS  -X POST --data-binary @"archive.tar.gz" -H 'Content-Type: application/octet-stream' -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://uploads.github.com/repos/jnaulty/openpgp-card-init/releases/$id/assets?name=openpgp-card-init_${{ github.ref_name }}_x86_64-apple-darwin.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETTLE_STATIC: "yes"

